name: ironoxide-cli

on: push

jobs:
  check:
    name: Check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Restore rust cache
        uses: actions/cache@v1
        with:
          key: ${{ github.workflow }}-rust-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ github.workflow }}-rust-
          path: ~/.cargo
      # Work around https://github.com/actions/cache/issues/133#issuecomment-599102035
      - run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/
        name: Remove .cargo/bin so we can restore it from cache
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
  fmt:
    name: Rustfmt
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  security:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Rust security audit
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
