name: CI

on:
  push:
    branches: main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-11, windows-2019]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.WORKFLOW_PAT }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Nix
        uses: cachix/install-nix-action@v17
      - name: Install Cachix
        uses: cachix/cachix-action@v10
        with:
          name: ironcorelabs-ironoxide-cli
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: echo yes | nix run github:cargo2nix/cargo2nix -- -f
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update Cargo.nix
      - name: Run CI
        run: 'nix build --print-build-logs --no-link .#ci'

  cargo-fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - run: cargo fmt --all -- --check
      - name: Cancel workflow
        if: failure()
        uses: andymckay/cancel-action@0.2
