name: CI

on:
  push:
    branches: main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-11, windows-2019]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: IronCoreLabs/rust-toolchain@v1
      - name: Test
        run: cargo test

  cargo-fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: IronCoreLabs/rust-toolchain@v1
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
      - name: Cancel workflow
        if: failure()
        uses: andymckay/cancel-action@0.2
