name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-11, windows-2019]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 99
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.WORKFLOW_PAT }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Nix
        uses: cachix/install-nix-action@v17
      - name: Install Cachix
        uses: cachix/cachix-action@v10
        with:
          name: ironcorelabs-ironoxide-cli
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      # - name: Test
      #   run: cargo test
      - name: Build
        run: nix build .#ironoxide-cli

  cargo-fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - run: cargo fmt --all -- --check
      - name: Cancel workflow
        if: failure()
        uses: andymckay/cancel-action@0.2
