name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        include:
          - os: windows-2019
            ext: .exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Package release artifacts
        working-directory: target/release
        run: mv ironoxide-cli${{ matrix.ext }} ironoxide-cli-${{ matrix.os }}${{ matrix.ext }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ matrix.os }}
          path: target/release/ironoxide-cli-${{ matrix.os }}${{ matrix.ext }}

  release:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt PGP key
        uses: IronCoreLabs/ironhide-actions/decrypt@v2
        with:
          keys: ${{ secrets.IRONHIDE_KEYS }}
          input: .github/signing-key.asc.iron
      - name: Import PGP key
        run: gpg --batch --import .github/signing-key.asc
      - uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Version ${{ github.ref }}

      - name: Download release artifacts from ubuntu-18.04
        uses: actions/download-artifact@v3
        with:
          name: release-ubuntu-18.04
          path: release/ubuntu-18.04
      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: release-ubuntu-18.04
          failOnError: false
      - name: Sign artifact for ubuntu-18.04
        run: |
          gpg --batch --detach-sign -a release/ubuntu-18.04/ironoxide-cli-ubuntu-18.04
          gpg --batch --verify release/ubuntu-18.04/ironoxide-cli-ubuntu-18.04.asc release/ubuntu-18.04/ironoxide-cli-ubuntu-18.04
      - name: Upload artifact for ubuntu-18.04
        run: gh release upload ${{ github.ref }} release/ubuntu-18.04/ironoxide-cli-ubuntu-18.04 release/ubuntu-18.04/ironoxide-cli-ubuntu-18.04.asc --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download release artifacts from macos-10.15
        uses: actions/download-artifact@v3
        with:
          name: release-macos-10.15
          path: release/macos-10.15
      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: release-macos-10.15
          failOnError: false
      - name: Sign artifact for macos-10.15
        run: |
          gpg --batch --detach-sign -a release/macos-10.15/ironoxide-cli-macos-10.15
          gpg --batch --verify release/macos-10.15/ironoxide-cli-macos-10.15.asc release/macos-10.15/ironoxide-cli-macos-10.15
      - name: Upload artifact for macos-10.15
        run: gh release upload ${{ github.ref }} release/macos-10.15/ironoxide-cli-macos-10.15 release/macos-10.15/ironoxide-cli-macos-10.15.asc --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download release artifacts from windows-2019
        uses: actions/download-artifact@v3
        with:
          name: release-windows-2019
          path: release/windows-2019
      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: release-windows-2019
          failOnError: false
      - name: Sign artifact for windows-2019
        run: |
          gpg --batch --detach-sign -a release/windows-2019/ironoxide-cli-windows-2019.exe
          gpg --batch --verify release/windows-2019/ironoxide-cli-windows-2019.exe.asc release/windows-2019/ironoxide-cli-windows-2019.exe
      - name: Upload artifact for windows-2019
        run: gh release upload ${{ github.ref }} release/windows-2019/ironoxide-cli-windows-2019.exe release/windows-2019/ironoxide-cli-windows-2019.exe.asc --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
